#!/usr/bin/tclsh
# This file defines the set of scripts (rules) that should be executed
# by default (if no specific profile is named when vera++ is launched).

#F001 ## Source files should not use the '\r' (CR) character
#F002 ## File names should be well-formed
#
#L001 ## No trailing whitespace
#L003 ## No leading and no trailing empty lines
#L004 ## Line cannot be too long (max 100)
#L005 ## There should not be too many consecutive empty lines (max 2)
#
#T001 ## One-line comments should not have forced continuation
#T002 ## Reserved names should not be used for preprocessor macros
#T003 ## Some keywords should be followed by a single space or semicolon (for = delete)
#T005 ## Keywords break and continue should be immediately followed by a semicolon
#T006 ## Keywords return and throw should be immediately followed by a semicolon or a single space
#T007 ## Semicolons should not be isolated by spaces or comments from the rest of the code
#T008 ## Keywords catch, for, if and while should be followed by a single space
#T009 ## Comma should not be preceded by whitespace, but should be followed by one
#T010 ## Identifiers should not be composed of 'l' and 'O' characters only
#T018 ## using namespace are not allowed in header files
#T019 ## control structures should have complete curly-braced block of code

set rules {
	F001
	F002

	L001
	L003
	L004
	L005

	T001
	T002
	T003
	T005
	T006
	T007
	T008
	T009
	T010
	T018
	T019
}
